### PR TITLE
Add support for rails 6

### PR DESCRIPTION
**Pull request by eduardohertz**
This PR contains:
- Support for rails 6
- Improved CircleCI configuration to test against multiple ruby versions

### CODE REVIEW

**Comment by cgriego** [comment]
Is there anything else needed to get this merged and released? @bradurani?

**Review by bradurani — APPROVED** [review]

**Comment by bradurani** [comment]
Hi guys, Somehow I didn't get a notification for this. Sorry for the delay. Looks great! Thank you!

**Comment by cgriego** [comment]
Thanks @bradurani! When do you think we'll see a release?

**Comment by mcasper** [comment]
Hey @cgriego, sorry for the wait here. I've just pushed up 1.3.0, which contains this fix

**Comment by cgriego** [comment]
@mcasper Can you push a release with the fix for 6.0.1+?

**Comment by mcasper** [comment]
@cgriego Just pushed 1.4.0!

**Comment by cgriego** [comment]
@mcasper Thank you!

**Pull request merged**
